- name: Nainstaluj balicky bison, flex, ...
  hosts: f135, f137
  remote_user: root
  tasks:
    - name: Install vim, mc, ...
      ansible.builtin.apt:
        update_cache: yes
        pkg:
        - vim
        - mc
        - flex
        - bison
