- name: Nainstaluj Java nastroje na vyvoj
  hosts: f135, f137
  remote_user: root
  tasks:
    - name: Install JDK17
      ansible.builtin.apt:
        name: openjdk-17-jdk
    - name: Install Maven
      ansible.builtin.apt:
        name: maven
    - name: Remove old Idea files
      ansible.builtin.file:
        path: /opt/idea
        state: absent
    - name: Copy and extract new Idea
      ansible.builtin.unarchive:
        src: files/ideaIC-2022.3.1.tar.gz
        dest: /opt/
    - name: Create symlink
      ansible.builtin.file:
        src: /opt/idea-IC-223.8214.52
        dest: /opt/idea
        state: link
    - name: Copy Idea desktop file
      ansible.builtin.copy:
        src: files/jetbrains-idea.desktop
        dest: /usr/share/applications/
    - name: Install DBeaver from the internet
      ansible.builtin.apt:
        deb: https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb

