- name: Nainstaluj Python nastroje na vyvoj
  hosts: f135, f137
  remote_user: root
  tasks:
    - name: Install Python3 (numpy)
      ansible.builtin.apt:
        update_cache: yes
        pkg:
        - python3-pip
        - python3-numpy
        - python3-pil
        - python3-matplotlib
        - python3-sdl2
        - python3-opengl
        - python3-opencv
        - python3-pygame
        - python3-serial
    - name: Install pynput package
      ansible.builtin.shell: pip3 install pynput
    - name: Remove old PyCharm files
      ansible.builtin.file:
        path: /opt/pycharm
        state: absent
    - name: Copy and extract new PyCharm
      ansible.builtin.unarchive:
        src: files/pycharm-community-2024.2.1.tar.gz
        dest: /opt/
    - name: Create symlink
      ansible.builtin.file:
        src: /opt/pycharm-community-2024.2.1
        dest: /opt/pycharm
        state: link
    - name: Copy PyCharm desktop file
      ansible.builtin.copy:
        src: files/jetbrains-pycharm.desktop
        dest: /usr/share/applications/

