- name: Debian update and upgrade
  hosts: f135, f137
  tasks:
   - name: Ping hosts
     ansible.builtin.ping:
   - name: Run the equivalent of "apt-get update"
     ansible.builtin.apt:
       update_cache: yes
   - name: Run the equivalent of "apt-get upgrade"
     ansible.builtin.apt:
       upgrade: safe
   - name: Run the equivalent of "apt-get dist-upgrade"
     ansible.builtin.apt:
       upgrade: full
    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: yes
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes
   - name: Print message
     ansible.builtin.debug:
       msg: Hello world

